"""empty message

Revision ID: 6e79b16f0bb3
Revises: 29ca02a44be5
Create Date: 2023-08-08 14:08:30.242882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e79b16f0bb3'
down_revision = '29ca02a44be5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invoices', sa.Boolean(), nullable=True))
    # Manual update
    op.execute("UPDATE items SET invoices = False")
    # ### end Alembic commands ###



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('invoices')

    # ### end Alembic commands ###
