"""empty message

Revision ID: 70be48ab4b42
Revises: 6e79b16f0bb3
Create Date: 2023-08-10 15:48:45.787043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70be48ab4b42'
down_revision = '6e79b16f0bb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(), nullable=False))
        batch_op.create_unique_constraint("email", ['email'])   # constraint name要給
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint("email", type_='unique')
        batch_op.drop_column('email')
    # ### end Alembic commands ###
